### ISSUE TITLE
Recommend Github Page About Section

### ISSUE THREAD

**Issue by vulnmaster** [casework/CASE-Mapping-Template-Stubs#7]
@ajnelson-nist I would like to recommend that we add a short description for this new repository. Here is my recommended text addition:

"This repository provides JSON-LD stubs and automation tools to assist adopters in implementing JSON-LD serialization for CASE and UCO ontology classes, facets, and properties."

**Comment by ajnelson-nist** [comment]
Added.  Thanks for pointing this out!
